DjangoPMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accommodations/', include('accommodation.urls')),
    path('reservation/', include('reservation.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('',views.index, name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),

]

reservation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='reservation'),
    path('accommodationssearch/', views.search, name='accommodationssearch'),
    path('accommodationslist/', views.search_results, name='accommodationslist'),
    path('accommodations/<int:pk>/reserve/', views.reserve, name='reserve'),
    path('invoice/<int:id>/', views.invoice, name='invoice'),
    path('reservations/', views.reservations, name='reservations'),
    path('reservations_view/<int:id>/', views.reservations_view, name='reservations_view'),
    path('reservations_delete/<int:id>', views.reservations_delete, name='reservations_delete'),
    path('reservations_list/', views.reservations_list, name='reservations_list'),
    path('reserve_search/', views.reserve_search, name='reserve_search'),
    path('leave_review/<int:id>/', views.leave_review, name='leave_review'),
    path('review_list/<int:id>/', views.review_list, name='review_list'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('', views.index, name='users'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('view/<int:id>', views.view, name='profile_view'),
    path('edit/<int:id>', views.edit, name='profile_edit'),
    path('delete/<int:id>', views.delete, name='profile_delete'),
    path("password_change", views.password_change, name="password_change"),
    path("request_staff", views.request_staff, name="request_staff"),
]

accommodation/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Country(models.Model):
    country_name = models.CharField(max_length=100, blank=False, null= False)
    country_code = models.CharField(max_length=6, blank=False, null=False)

    def __str__(self):
        return self.country_name

class City(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False)
    postcode = models.CharField(max_length=5, blank=False, null=False)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name        

class Accommodation(models.Model):
    name = models.CharField(max_length=100, blank=False, null= False)
    description = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=100, blank=False, null= False)
    email= models.EmailField()
    phone = models.CharField(max_length=12, blank=True, null=True)
    mobile = models.CharField(max_length=12, blank=False, null=False)
    default_image = models.ImageField(blank=False, null=False, upload_to="images/")
    is_active = models.BooleanField(default=False)
    default_price = models.DecimalField(max_digits=8, decimal_places=2)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


    def get_price(self, start_date, end_date):
        price = Price.objects.filter(accommodation=self, start_date__lte=start_date, end_date__gte=end_date).first()
        if price:
            return price.price
        else:
            # si no se encuentra un precio específico, devuelve el precio por defecto del alojamiento
            return self.default_price    

class Image(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')            

class Price(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f'{self.accommodation} - {self.start_date} - {self.end_date} - {self.price}'
      



dashboard/models.py
from django.db import models

# Create your models here.

reservation/forms.py
from django import forms
from accommodation.models import Country, City
from reservation.models import Reservation, Review
from django.forms import DateInput

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['start_date', 'end_date',]

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget = forms.DateInput(attrs={'type': 'date'})
        self.fields['end_date'].widget = forms.DateInput(attrs={'type': 'date'})

class SearchForm(forms.Form):
    fecha_inicio = forms.DateField(widget=DateInput(attrs={'type': 'date'}), required=False)
    fecha_fin = forms.DateField(widget=DateInput(attrs={'type': 'date'}),required=False) 
    pais = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        required=False,
        empty_label="Mostrar Todos"
    )
    ciudad = forms.ModelChoiceField(
        queryset=City.objects.all(),
        required=False,
        empty_label="Mostrar Todas"
    )

class PaymentForm(forms.Form):
    metodo_de_pago = forms.ChoiceField(choices=[
        ('tarjeta_credito', 'Tarjeta de Crédito'),
        ('tarjeta_debito', 'Tarjeta de Débito'),
        ('transferencia_bancaria', 'Transferencia Bancaria'),
        ('en_hotel', 'Pago en Hotel')
    ])
    fecha_inicio = forms.DateField(widget=DateInput(attrs={'type': 'date'}))
    fecha_fin = forms.DateField(widget=DateInput(attrs={'type': 'date'}))

from django import forms

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'title', 'review']
        labels = {
                'rating': 'calificación',
                'title': 'titulo',
                'review': 'reseña',
                }

    rating = forms.IntegerField(min_value=1, max_value=5)
    title = forms.CharField(max_length=255)
    review = forms.CharField(widget=forms.Textarea)  

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from reservation.models import Reservation
from accommodation.models import Accommodation

# Create your views here.
def index(request):
    return render(request, 'index.html', {})

@login_required
def dashboard(request):
    # Numero de reservas
    reservations = Reservation.objects.filter(accommodation__user=request.user).count()
    # Numero de alojamientos creados
    accommodations = Accommodation.objects.filter(user=request.user).count()
    # Numero de reservas realizadas por el usuario
    user_reservations = Reservation.objects.filter(user=request.user).count()

    context = {
        'reservations': reservations,
        'accommodations': accommodations,
        'user_reservations': user_reservations,
    }
    return render(request, 'reservations/dashboard.html', context)

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accommodation.models import Accommodation, Price
from reservation.models import Payment, Review, Reservation
from django.contrib import messages
from .forms import PaymentForm, SearchForm, ReviewForm
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from datetime import date
from django.db.models import Avg


# Create your views here.


def index(request):
    return render(request, 'index.html', {})


@login_required
def search(request):
    form = SearchForm()
    return render(request, 'reservations/partials/searchdate.html', {'form': form})


@login_required
def search_results(request):
    # Mostrar todos los alojamientos al principio
    accommodations = Accommodation.objects.filter(is_active=True)
    start_date = None
    end_date = None
    country = None
    city = None
    # Si se ha enviado el formulario, procesar la búsqueda
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data["fecha_inicio"]
            end_date = form.cleaned_data["fecha_fin"]
            country = form.cleaned_data["pais"]
            city = form.cleaned_data["ciudad"]
            # Filtrar los alojamientos disponibles en el rango de fechas especificado
            if start_date and end_date:
                reservations = Reservation.objects.filter(
                    start_date__lte=end_date, end_date__gte=start_date)
                accommodations = accommodations.exclude(reservation__in=reservations)
            if country:
                accommodations = accommodations.filter(country=country)
            if city:
                accommodations = accommodations.filter(city=city)
    # Enviar los alojamientos filtrados a la plantilla
    context = {
        'accommodations': accommodations,
        'start_date': start_date,
        'end_date': end_date
    }
    return render(request, 'accommodations/list.html', context)

@login_required
def reserve_search(request):
    active_accommodations = Accommodation.objects.filter(
        name__contains=request.GET.get('search', ''))
    context = {
        'accommodations': active_accommodations,
    }
    return render(request, 'accommodations/list.html', context)    

@login_required
def accommodations_list(request):
    active_accommodations = Accommodation.objects.filter(is_active=True).annotate(average_rating=Avg('review__rating'))
    context = {
        'accommodations': active_accommodations
    }
    return render(request, 'accommodations/list.html', context)



def process_payment(payment_method):
    if payment_method == "en_hotel":
        # Si el pago se realizará en el hotel, no hace falta procesar el pago
        return "Pendiente"
    else:
        # Si el pago se realizará con otro método, asumir que el pago ha sido exitoso
        return "Pagado"


@login_required
def reserve(request, pk):
    accommodation = get_object_or_404(Accommodation, pk=pk)
    payment_form = PaymentForm()
    if request.method == "POST":
        form = PaymentForm(request.POST)
        if form.is_valid():
            payment_method = form.cleaned_data["metodo_de_pago"]
            # Procesar el pago utilizando la función process_payment
            status = process_payment(payment_method)
            start_date = form.cleaned_data["fecha_inicio"]
            end_date = form.cleaned_data["fecha_fin"]
            if not Reservation.is_available(accommodation, start_date, end_date):
                messages.error(request, "Lo sentimos, este alojamiento no está disponible en esas fechas.")
                return redirect("accommodations")
            # Utilizar el método get_price para obtener el precio correcto
            price = accommodation.default_price
            total_price = price * (end_date - start_date).days    
            # Crear una instancia del modelo Reservation
            reservation = Reservation(
                start_date=start_date,
                end_date=end_date,
                accommodation=accommodation,
                user=request.user,
                total_price=total_price,
            )
            reservation.save()
            # Crear una instancia del modelo Payment
            payment = Payment(
                reservation=reservation,
                payment_method=payment_method,
                amount=total_price,
                status=status
            )
            payment.save()
            messages.success(request, "Reserva realizada con éxito.")
            return redirect("reservations")
    else:
        form = PaymentForm()
    return render(request, "reservations/reserve.html", {"form": form, "payment_form": payment_form, "accommodation": accommodation,})


@login_required
def invoice(request, id):
    reservation = get_object_or_404(Reservation, id=id)
    payment = Payment.objects.get(reservation=reservation)
    reservation = payment.reservation
    number_of_nights = (reservation.end_date - reservation.start_date).days
    net_total_price = (reservation.total_price / Decimal(1.21))
    iva = reservation.total_price - net_total_price
    context = {
        'payment': payment,
        'reservation': reservation,
        'number_of_nights': number_of_nights,
        'net_total_price': net_total_price,
        'iva': iva,
    }
    return render(request, 'reservations/invoice.html', context)

@login_required
def leave_review(request, id):
    reservation = get_object_or_404(Reservation, id=id)
    # Comprobar que la fecha de hoy es superior a la fecha de salida antes de permitir la publicación de una reseña
    if date.today() <= reservation.end_date:
        messages.error(request, 'Solo puedes publicar una reseña cuando se complete la estancia')
        return redirect('reservations')
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            # Guardar la reseña en la base de datos y asociarla con la reserva correspondiente
            review = form.save(commit=False)
            review.reservation = reservation
            review.user = request.user
            review.accommodation = reservation.accommodation #Aquí estableces la relación con la columna "accommodation_id"
            review.save()
            messages.success(request, 'Reseña publicada')
            return redirect('reservations')
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'reservation': reservation,
    }
    return render(request, 'reservations/leave_review.html', context) 

@login_required  
def review_list(request,id):
    accommodation = get_object_or_404(Accommodation, id=id)
    reviews = Review.objects.filter(accommodation=accommodation)
    if not reviews:
        message = "No hay reseñas publicadas todavía."
    else:
        message = ""
    context = {
        'reviews': reviews, 
        'message': message,
        'accommodation':accommodation}
    return render(request, 'reservations/review_list.html', context)

@login_required
def reservations(request):
    current_user = request.user
    reservations = Reservation.objects.filter(
        id__contains=request.GET.get('search', ''))
    context = {
        'current_user': current_user,
        'reservations': reservations
    }
    return render(request, 'reservations/reservations.html', context)


@login_required
def reservations_view(request, id):
    reservations = Reservation.objects.get(id=id)
    number_of_nights = (reservations.end_date - reservations.start_date).days
    context = {
        'reservations': reservations,
        'number_of_nights': number_of_nights,
    }
    return render(request, 'reservations/detail.html', context)

@login_required
def reservations_delete(request, id):
    reservations = Reservation.objects.get(id=id)
    reservations.delete()
    messages.success(request, 'Reserva cancelada')
    return redirect('reservations')


@login_required
def reservations_list(request):
    # Obtener los alojamientos del usuario actual
    accommodations = Accommodation.objects.filter(user=request.user)

    # Si el usuario tiene alojamientos, obtener las reservas de esos alojamientos
    if accommodations:
        reservations = Reservation.objects.filter(accommodation__in=accommodations)
    else:
        reservations = None

    return render(request, 'reservations/reservations_list.html', {
        'accommodations': accommodations,
        'reservations': reservations,
    })



templates/reservations/dashboard.html
{% extends 'layout/base.html' %}
 
{% block 'title' %}Cuadro de Mando {% endblock 'title' %}

{% block 'content' %}
<h1>Cuadro de Mando</h1>
<ul class="list">
   <li><b>Número de reservas en mis alojamientos: </b>{{ reservations }}</li>
   <li><b>Número de alojamientos creados: </b>{{ accommodations }}</li>
   <li><b>Número de reservas realizadas por mi: </b>{{ user_reservations }}</li>
</ul>
{% endblock 'content' %}

templates/reservations/detail.html
{% extends 'layout/base.html' %}
 
{% block 'title' %}Detalle de la reserva {{ reservations.id }}{% endblock 'title' %}

{% block 'content' %}

<ul class="list">
   <li><img src ="{{ reservations.accommodation.default_image.url }}"width="250" height="250">
      <a href="{% url 'view_images' id=reservations.accommodation.id %}" class="btn btn-edit">Ver galería de imágenes</a></li>
   <li><b>Nombre del Hotel: </b>{{ reservations.accommodation.name }}</li>
   <li><b>Fecha de entrada: </b>{{ reservations.start_date }}</li>
   <li><b>Fecha de salida: </b>{{ reservations.end_date }}</li>
   <li><b>Precio por noche: </b>{{ reservations.accommodation.price|floatformat:2}} €</li>
   <li><b>Total noches: </b>{{ number_of_nights}}</li>
   <li><b>Precio total: </b>{{ reservations.total_price|floatformat:2 }} €</li>
</ul>
{% endblock 'content' %}

templates/reservations/invoice.html
{% extends 'layout/base.html' %}

{% block 'title' %}Invoice{% endblock 'title' %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
{% endblock %}

{% block 'content' %}

<div class="invoice-container">
  <div class="header">
    <table class="invoice">
      <tr>
        <td class="company-details" colspan="2">
          <h2>Datos empresa</h2>
          <p>Empresa: Property Management System</p>
          <p>Dirección: Calle Madrid, 5</p>
          <p>Ciudad: Alicante</p>
          <p>Código Postal: 03007</p>
          <p>CIF: BXXXXXXXX</p>
        </td>
        <td class="client-details" colspan="2">
          <h2>Datos del cliente</h2>
          <p>Nombre de usuario: {{ reservation.user.username }}</p>
          <p>Nombre: {{ reservation.user.first_name }}</p>
          <p>Apellidos: {{ reservation.user.last_name }}</p>
          <p>Email: {{ reservation.user.email }}</p>
        </td>
      </tr>
    </table>
  </div>
  <div class="invoice-details">
    <table class="invoice">
      <tr>
        <td>
          <h2>Datos de factura</h2>
          <p>Fecha factura: {{ payment.created_at }}</p>
          <p>Factura nº: {{ reservation.id }}</p>
        </td>
      </tr>
    </table>
  </div>
  <hr>
  <div class="reservation-details">
    <table class="invoice">
      <tr>
        <th style="width: 25%;">Hotel</th>
        <td style="width: 75%;">{{ reservation.accommodation.name }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Fecha de entrada</th>
        <td style="width: 75%;">{{ reservation.start_date }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Fecha de salida</th>
        <td style="width: 75%;">{{ reservation.end_date }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Número de noches</th>
        <td style="width: 75%;">{{ number_of_nights }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Importe por noche (IVA incluido)</th>
        <td style="width: 75%;">{{ reservation.accommodation.default_price|floatformat:2 }} €</td>
      </tr>
    </table>
  </div>
  <hr>
  <div class="payment-details">
    <table class="invoice">
      <tr>
        <th style="width: 25%;">Método de pago</th>
        <td style="width: 75%;">{{ payment.payment_method }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Estado de pago</th>
        <td style="width: 75%;">{{ payment.status }}</td>
      </tr>
      <tr>
        <th style="width: 25%;">Precio total sin IVA</th>
        <td style="width: 75%;">{{ net_total_price|floatformat:2 }} €</td>
      </tr>
      <tr>
        <th style="width: 25%;">IVA (21%)</th>
        <td style="width: 75%;">{{ iva|floatformat:2 }} €</td>
      </tr>
      <tr>
        <th style="width: 25%;">Precio total de la reserva (IVA incluido)</th>
        <td style="width: 75%;">{{ reservation.total_price|floatformat:2 }} €</td>
      </tr>
    </table>
  </div>
</div>
{% endblock %}

templates/reservations/leave_review.html
{% extends 'layout/base.html' %}
 
{% block 'title' %}Reseña{% endblock 'title' %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block 'content' %}
<div class="container">
    <h1>Reseña</h1>
    <span class="btn-back"><a href="{% url 'reservations' %}">Volver atrás</a></span>
    <form method="post">
        {% csrf_token %}
        <div class="hotel-info">
            <p>Hotel: {{ reservation.accommodation }}</p>
        </div>
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-reserve">Enviar Reseña</button>
    </form>
</div>
{% endblock 'content' %}

templates/reservations/pay.html
{% extends 'layout/base.html' %}

{% block 'title' %}Realizar Pago{% endblock 'title' %}

{% block 'content' %}

<h1>Confirmar método de pago</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Pagar</button>
</form>
{% endblock 'content' %}

templates/reservations/reservations.html
 
 {% extends 'layout/base.html' %}
 
 {% block 'title' %}Reservas{% endblock 'title' %}

 {% block 'content' %}
 <h1>Mis reservas</h1>
 <ul class="list">
    

    {% for reservation in reservations  %}
        {% if reservation.user == request.user %}
            <li>
                <img src="{{ reservation.accommodation.default_image.url }}" width="100" height="100">
                <div class="list-item">
                    <p><strong>Alojamiento:</strong> {{ reservation.accommodation.name }}</p>
                    <p><strong>Fecha de entrada:</strong> {{ reservation.start_date }}</p>
                    <p><strong>Fecha de salida:</strong> {{ reservation.end_date }}</p>
                </div>
                <span> 
                    <a href={% url 'reservations_view' id=reservation.id %} class="btn btn-detail">
                      <i class="fas fa-eye"></i> Ver
                    </a> 
                    <a href={% url 'invoice' id=reservation.id %} class="btn btn-detail">
                      <i class="fas fa-file-invoice"></i> Visualizar Factura
                    </a> 
                    <a  href={% url 'reservations_delete' id=reservation.id %} onclick="return confirm('¿Estás seguro de querer cancelar la reserva?')" class="btn btn-delete">
                      <i class="fas fa-times"></i> Cancelar Reserva
                    </a>
                    <a href={% url 'leave_review' id=reservation.id %} class="btn btn-edit">
                      <i class="fas fa-star"></i> Publicar Reseña
                    </a>
                </span>
            </li>
    
        {% endif %}
    {% endfor %}
 </ul>
 {% endblock 'content' %}

templates/reservations/reservations_list.html
{% extends 'layout/base.html' %}

{% block 'title' %}Reservas{% endblock 'title' %}

{% block 'content' %}
<h1>Reservas en mis alojamientos</h1>
{% if accommodation_set.count == 0 %}
    <p>No tienes alojamientos creados todavía.</p>
{% else %}
    {% if reservations.count == 0 %}
        <p>No tienes reservas realizadas en tus alojamientos.</p>
    {% else %}
        <ul class="list">
            {% for reservation in reservations  %}
                <li>
                    <div class="list-item">
                        <img src="{{ reservation.accommodation.default_image.url }}" width="100" height="100">
                    </div>
                    <div class="list-item">
                        <p><strong>Alojamiento:</strong> {{ reservation.accommodation.name }}</p>
                        <p><strong>Fecha de entrada:</strong> {{ reservation.start_date }}</p>
                        <p><strong>Fecha de salida:</strong> {{ reservation.end_date }}</p>
                        <p><strong>Usuario que realizó la reserva:</strong> {{ reservation.user.username }}</p>
                    </div>
                    <div class="list-item">
                        <span>
                            <a href={% url 'reservations_view' id=reservation.id %} class="btn btn-detail"><i class="fas fa-eye"></i>Ver</a> 
                            <a href={% url 'invoice' id=reservation.id %} class="btn btn-detail"><i class="fas fa-file"></i>Ver Factura</a> 
                            <a  href={% url 'reservations_delete' id=reservation.id %} onclick="return confirm('¿Estás seguro de querer cancelar la reserva?')" class="btn btn-delete"><i class="fas fa-trash"></i>Cancelar Reserva</a>
                        </span>
                    </div>
                </li>
                <hr>
            {% endfor %}
        </ul>
    {% endif %}
{% endif %}
{% endblock 'content' %}

templates/reservations/reserve.html
{% extends 'layout/base.html' %}
 
{% block 'title' %}Realiza una reserva{% endblock 'title' %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block 'content' %}
<div class="container">
    <h1>Confirmar fechas de reserva</h1>
    <span class="btn-back"><a href="{% url 'accommodationslist' %}">Volver atrás</a></span>
    <form method="post">
        {% csrf_token %}
        <div class="hotel-info">
            <p>Hotel: {{ accommodation }}</p>
            <p>Precio por noche: {{ accommodation.default_price|floatformat:2 }} €</p>
        </div>
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-reserve">Confirmar reserva</button>
    </form>
</div>
{% endblock 'content' %}

templates/reservations/review_list.html
{% extends 'layout/base.html' %}

{% block 'title' %}Reseñas{% endblock 'title' %}
{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block 'content' %}
<h1>Reseñas</h1>
<span class="aux-btns"><a href="{% url 'accommodationslist' %}">Volver</a></span>
<h1>{{ message }}</h1>
<ul class="list">
    {% for review in reviews %}
        <li>
            <div class="review-header">
                <img src="{{ review.accommodation.default_image.url }}" width="100" height="100" alt="Imagen del alojamiento">
                <h3 class="review-accommodation-name">{{ review.accommodation.name }}</h3>
                <div class="star-rating"></div>
              </div>
            <div class="review-content">
                <p class="review-title">Calificación: <span class="review-info">{{ review.rating }}</span></p>
                <p class="review-title">Título: <span class="review-info">{{ review.title }}</span></p>
                <p class="review-title">Reseña: <span class="review-info">{{ review.review }}</span></p>
                <p class="review-title">Fecha de publicación: <span class="review-info">{{ review.date_created }}</span></p>
            </div>
            <hr>
        </li>        
    {% endfor %}
</ul>
{% endblock 'content' %}